### ISSUE TITLE
Print jobs fail to print when Windows username contains a space.

### ISSUE THREAD

**Issue by stop-error** [Libki/libki-print-manager#1]
When Libki Print Manager runs the command:

`SumatraPDF.exe -silent  -print-settings "color,simplex" -print-to TEST-PRINTER C:/Users/User Name/AppData/Local/Temp/color/3.pdf`

It will fail, as `C:/Users/User Name/AppData/Local/Temp/color/3.pdf` contains a space and is not quoted.

**Comment by kylemhall** [comment]
@stop-error can you test version 1.3.1 to see if that fixes the issue?

**Comment by sekjal** [comment]
Closing this after 6 months
